### PR TITLE
Fix typings

### PR DESCRIPTION
**Pull request by Bernix01**

### CODE REVIEW

**Comment by schlunsen** [comment]
HI, thanks for the pull request.

I'm not a typescript user, but could you explain briefly why this is needed?

**Comment by Bernix01** [comment]
Testing locally, the typings file was not included in the `files` section of `package.json`. I added it and moved them to a `types`folder. 
The down side is that now it may be added as “@nuxt-leaflet/types” 
Let me undo some changes so we can keep the documented way of adding it to `tsconfig.json`

**Comment by Bernix01** [comment]
To summarize:
Just added the typings file to de `files` sections. Now when you install the package, the typings will be included.

**Comment by schlunsen** [comment]
Thanks for your work! World you be interested in doing an advanced example using typescript for this repo? I’ll publish to npm later tonight

**Comment by Bernix01** [comment]
Sorry but I'm starting to learn with leaflet, my knowledge is very basic. Once I finish my current project (which involves leaflet), sure will do.

**Pull request merged**
